# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lost_dutchman.proto

require 'google/protobuf'


descriptor_data = "\n\x13lost_dutchman.proto\x12\rlost_dutchman\"\'\n\x0fNextPageRequest\x12\x14\n\x0c\x63urrent_host\x18\x01 \x01(\t\")\n\x10NextPageResponse\x12\x15\n\rnext_page_url\x18\x01 \x01(\t\"|\n\x0c\x43rawlOutcome\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x02 \x01(\t\x12\x16\n\x0e\x63ontent_length\x18\x03 \x01(\x05\x12\x15\n\rlast_modified\x18\x04 \x01(\t\x12\x0c\n\x04\x65tag\x18\x05 \x01(\t\x12\x0c\n\x04\x63ode\x18\x06 \x01(\x05\"\'\n\x14\x43rawlOutcomeResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xbe\x01\n\tConductor\x12W\n\x12GetNextPageToCrawl\x12\x1e.lost_dutchman.NextPageRequest\x1a\x1f.lost_dutchman.NextPageResponse\"\x00\x12X\n\x12ReportCrawlOutcome\x12\x1b.lost_dutchman.CrawlOutcome\x1a#.lost_dutchman.CrawlOutcomeResponse\"\x00\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module LostDutchman
  NextPageRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("lost_dutchman.NextPageRequest").msgclass
  NextPageResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("lost_dutchman.NextPageResponse").msgclass
  CrawlOutcome = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("lost_dutchman.CrawlOutcome").msgclass
  CrawlOutcomeResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("lost_dutchman.CrawlOutcomeResponse").msgclass
end
